/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    CtaSection: typeof import('./components/CtaSection.vue')['default']
    FeaturesSection: typeof import('./components/FeaturesSection.vue')['default']
    ForBusinessSection: typeof import('./components/ForBusinessSection.vue')['default']
    ForCouriersSection: typeof import('./components/ForCouriersSection.vue')['default']
    HeroSection: typeof import('./components/HeroSection.vue')['default']
    HowItWorksSection: typeof import('./components/HowItWorksSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
